# Loading Libraries and Dataset

In [169]:
# Installing and loading libraries
import pandas as pd
import numpy as np

# For imputing missing values
from sklearn.ensemble import RandomForestRegressor

In [170]:
# Loading the CSV dataset
df = pd.read_csv("Dataset/CubanDataset.csv")

# Viewing The Data

In [171]:
# Viewing a portion of the dataset
df.head()

id  age  menarche menopause agefirst children breastfeeding         nrelbc  \
0   1   50        11        No       No        0            No         Mother   
1   2   46        12        No       36        1      3 months  Mother/Sister   
2   3   47        13        No       26        1      3 months         Sister   
3   4   49        11        47       21        1            No       Daughter   
4   5   54        14        42       16        1       1 month         Mother   

   biopsies hyperplasia  ... weight  exercise  alcohol  tobacco   allergies  \
0       1.0         Yes  ...   83.4        No      Yes      Yes    Rhinitis   
1       2.0         Yes  ...   78.2         2      Yes       No   Medicines   
2       1.0         Yes  ...   82.6         1       No      Yes  Laryngitis   
3       1.0          No  ...   79.4        No      Yes      Yes          No   
4       2.0         Yes  ...   81.5        No      Yes       No          No   

  emotional depressive histologicalclass birads cancer  
0       Sad        Yes               3.0     3A    Yes  
1       Joy         No               3.0     3B    Yes  
2       Sad         No               4.0     3B    Yes  
3       Joy         No               3.0     4B    Yes  
4       Sad        Yes               4.0     3C    Yes  

[5 rows x 23 columns]

In [172]:
# Viewing the shape of the dataset
df.shape

(1697, 23)

In [173]:
# Viewing the datatype of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1697 entries, 0 to 1696
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 1697 non-null   int64  
 1   age                1697 non-null   int64  
 2   menarche           1697 non-null   int64  
 3   menopause          1697 non-null   object 
 4   agefirst           1697 non-null   object 
 5   children           1697 non-null   object 
 6   breastfeeding      1697 non-null   object 
 7   nrelbc             1697 non-null   object 
 8   biopsies           1696 non-null   float64
 9   hyperplasia        1697 non-null   object 
 10  race               1697 non-null   object 
 11  year               1160 non-null   float64
 12  imc                1690 non-null   float64
 13  weight             1687 non-null   float64
 14  exercise           1697 non-null   object 
 15  alcohol            1697 non-null   object 
 16  tobacco            1697 

In [174]:
# Viewing the statistics of numerical data
df.describe()

id          age     menarche     biopsies         year  \
count  1697.00000  1697.000000  1697.000000  1696.000000  1160.000000   
mean    849.00000    51.483206    11.725987     1.308373  2010.863793   
std     490.02602    11.929919     1.839937     1.184392     4.636249   
min       1.00000    20.000000     8.000000     0.000000  2001.000000   
25%     425.00000    45.000000    10.000000     0.000000  2008.000000   
50%     849.00000    53.000000    12.000000     1.000000  2011.000000   
75%    1273.00000    61.000000    13.000000     2.000000  2015.000000   
max    1697.00000    90.000000    17.000000     5.000000  2018.000000   

               imc       weight  histologicalclass  
count  1690.000000  1687.000000        1160.000000  
mean     25.534615    70.497214           3.729310  
std       4.961554    12.808854           1.767066  
min       5.000000    13.000000           1.000000  
25%      22.800000    61.900000           3.000000  
50%      25.100000    69.200000           3.000000  
75%      27.300000    79.200000           4.000000  
max      88.800000   240.000000          11.000000

In [175]:
# Viewing the unique values of categorical data
df.select_dtypes(include = "object").apply(pd.unique)

menopause        [No, 47, 42, 44, 46, 43, 51, 40, 41, 48, 39, 4...
agefirst         [No, 36, 26, 21, 16, 20, 27, 24, 30, 35, 25, 1...
children                                    [0, 1, 2, 3, 4, 5, 5+]
breastfeeding    [No, 3 months, 1 month, 2 months, 4 months, 8 ...
nrelbc           [Mother, Mother/Sister, Sister, Daughter, No, ...
hyperplasia                                              [Yes, No]
race                                         [White, Mixed, Black]
exercise                   [No, 2, 1, Diary, 3, 5, 4, NO, 6, 0, 7]
alcohol                                                  [Yes, No]
tobacco                                                  [Yes, No]
allergies        [Rhinitis, Medicines, Laryngitis, No, Dermatit...
emotional                                               [Sad, Joy]
depressive                                               [Yes, No]
birads                            [3A, 3B, 4B, 3C, 5C, 5B, 6, nan]
cancer                                                   [Yes,

In [176]:
# Viewing the amount of distinct values in each column
df.select_dtypes(include = "object").nunique()

menopause        29
agefirst         33
children          7
breastfeeding    42
nrelbc           18
hyperplasia       2
race              3
exercise         11
alcohol           2
tobacco           2
allergies        24
emotional         2
depressive        2
birads            7
cancer            2
dtype: int64

In [177]:
# Viewing the amount of null values in each column
df.isnull().sum()

id                     0
age                    0
menarche               0
menopause              0
agefirst               0
children               0
breastfeeding          0
nrelbc                 0
biopsies               1
hyperplasia            0
race                   0
year                 537
imc                    7
weight                10
exercise               0
alcohol                0
tobacco                0
allergies            276
emotional              0
depressive             0
histologicalclass    537
birads               537
cancer                 0
dtype: int64

# Data Preprocessing

## Cleaning messy data
Columns processed: "menopause", "agefirst", "breastfeeding", "exercise"

In [178]:
# Viewing the unique values of the menopause column
df["menopause"].unique()

array(['No', '47', '42', '44', '46', '43', '51', '40', '41', '48', '39',
       '49', '45', '50', '37', '52', '38', '32', '0', '33', '55', '53',
       '35', '54', '30', '60', '56', '34', '36'], dtype=object)

In [179]:
# Changing menopause column's datatype into integer and replacing the "No" value with -1
df["menopause"] = df["menopause"].replace(["No", "0"], -1).astype(int)
df["menopause"].unique()

array([-1, 47, 42, 44, 46, 43, 51, 40, 41, 48, 39, 49, 45, 50, 37, 52, 38,
       32, 33, 55, 53, 35, 54, 30, 60, 56, 34, 36])

In [180]:
# Viewing the unique values of the agefirst column
df["agefirst"].unique()

array(['No', '36', '26', '21', '16', '20', '27', '24', '30', '35', '25',
       '18', '28', '23', '22', '17', '29', '19', '31', '14', '34', '33',
       '39', '32', '37', '38', '15', '0', '43', '46', '40', '10', '9'],
      dtype=object)

In [181]:
# Changing agefirst column's datatype into integer and replacing the "No" value with -1
df["agefirst"] = df["agefirst"].replace(["No", "0"], -1).astype(int)
df["agefirst"].unique()

array([-1, 36, 26, 21, 16, 20, 27, 24, 30, 35, 25, 18, 28, 23, 22, 17, 29,
       19, 31, 14, 34, 33, 39, 32, 37, 38, 15, 43, 46, 40, 10,  9])

In [182]:
# Viewing the unique values of the breastfeeding column
df["breastfeeding"].unique()

array(['No', '3 months', '1 month', '2 months', '4 months', '8 months',
       '6 months', '5 months', '7 months', '10 months', '9 months', 'No ',
       '1 month ', '12 months', '6', '2', '10', '8', '0', '7', '4', '3',
       '5', '12', '11', '18', '16', '36', '15', '1', '72', '13', '24',
       '9', '48', '14', '17', '22', '26', '25', '28', '21'], dtype=object)

In [183]:
# Cleaning the breastfeeding column's data
# Replacing the "No" and "No " value with -1
df["breastfeeding"] = df["breastfeeding"].replace(["No", "No ", "0"], -1)

# Removing month(s) string suffixes
df["breastfeeding"] = df["breastfeeding"].astype(str).str.replace(r" months?", "", regex = True) # (Operation converts datatype to string)

# Converting column datatype into integer
df["breastfeeding"] = df["breastfeeding"].astype(int)
df["breastfeeding"].unique()

array([-1,  3,  1,  2,  4,  8,  6,  5,  7, 10,  9, 12, 11, 18, 16, 36, 15,
       72, 13, 24, 48, 14, 17, 22, 26, 25, 28, 21])

In [184]:
# Viewing the unique values of the exercise column
df["exercise"].unique()

array(['No', '2', '1', 'Diary', '3', '5', '4', 'NO', '6', '0', '7'],
      dtype=object)

In [185]:
# Viewing the count of each unique value of the exercise column
df["exercise"].value_counts()

exercise
No       712
0        394
2        206
3        162
1        113
5         34
Diary     28
4         24
7         14
NO         5
6          5
Name: count, dtype: int64

In [186]:
# Replacing the 0, "No", and "NO" value with -1
df["exercise"] = df["exercise"].replace(["No", "NO", "0"], -1)

# Replacing the "Diary" value with 0 and changing exercise column's datatype into integer
df["exercise"] = df["exercise"].replace("Diary", 0).astype(int)

df["exercise"].unique()

array([-1,  2,  1,  0,  3,  5,  4,  6,  7])

## Creating new binary columns to help identify data with multiple values
Columns processed: "nrelbc", "allergies"

In [187]:
# Viewing the unique values of the nrelbc column
df["nrelbc"].unique()

array(['Mother', 'Mother/Sister', 'Sister', 'Daughter', 'No',
       'Mother/Daughter', 'Sister/Daughter', 'Cousin', 'Aunt',
       'Grandmother', 'Mother/Grandmother', 'Aunt/Cousin',
       'Grandmother/Aunt', 'Sister/Grandmother', 'Grandmother ',
       'Mother/Aunt', 'Mother/Aunt/Cousin',
       'Mother/Grandmother/Aunt/Cousin'], dtype=object)

In [188]:
# Creating new columns to identify which relatives has experienced breast cancer before
# Identifying available values
familyMembers = ["Mother", "Sister", "Daughter", "Cousin", "Aunt", "Grandmother", "No"]

# Creating the new columns
for member in familyMembers:
    df[member] = df["nrelbc"].str.contains(member).astype(int)

# Dropping the original column
df.drop(columns = ["nrelbc"], inplace = True)

In [189]:
# Renaming the result columns
df = df.rename(columns = {
    "Mother" : "nrelbc_mother",
    "Sister" : "nrelbc_sister",
    "Daughter" : "nrelbc_daughter",
    "Cousin" : "nrelbc_cousin",
    "Aunt" : "nrelbc_aunt",
    "Grandmother" : "nrelbc_grandma",
    "No" : "nrelbc_absent"
})

In [190]:
# Viewing the amount of unique values in each column
df.nunique()

id                   1697
age                    61
menarche               10
menopause              28
agefirst               32
children                7
breastfeeding          28
biopsies                6
hyperplasia             2
race                    3
year                   18
imc                   188
weight                292
exercise                9
alcohol                 2
tobacco                 2
allergies              24
emotional               2
depressive              2
histologicalclass      11
birads                  7
cancer                  2
nrelbc_mother           2
nrelbc_sister           2
nrelbc_daughter         2
nrelbc_cousin           2
nrelbc_aunt             2
nrelbc_grandma          2
nrelbc_absent           2
dtype: int64

In [191]:
# Viewing data with missing allergies value
df[df["allergies"].isna()]

id  age  menarche  menopause  agefirst children  breastfeeding  \
1160  1161   61        13         48        29        1              6   
1165  1166   54         9         33        29        2              7   
1167  1168   62        11         52        20        3              4   
1168  1169   55        10         53        23        2              3   
1169  1170   74        10         50        25        2              7   
...    ...  ...       ...        ...       ...      ...            ...   
1687  1688   20        13         -1        -1        0             -1   
1689  1690   45        12         -1        26        2              8   
1690  1691   21        12         -1        -1        0             -1   
1691  1692   21        12         -1        -1        0             -1   
1693  1694   21        12         -1        -1        0             -1   

      biopsies hyperplasia   race  ...  histologicalclass  birads  cancer  \
1160       0.0          No  Mixed  ...                NaN     NaN      No   
1165       0.0          No  Mixed  ...                NaN     NaN      No   
1167       0.0          No  Mixed  ...                NaN     NaN      No   
1168       0.0          No  Mixed  ...                NaN     NaN      No   
1169       0.0          No  Black  ...                NaN     NaN      No   
...        ...         ...    ...  ...                ...     ...     ...   
1687       0.0          No  Mixed  ...                NaN     NaN      No   
1689       0.0          No  White  ...                NaN     NaN      No   
1690       0.0          No  White  ...                NaN     NaN      No   
1691       0.0          No  Black  ...                NaN     NaN      No   
1693       0.0          No  White  ...                NaN     NaN      No   

      nrelbc_mother nrelbc_sister nrelbc_daughter nrelbc_cousin nrelbc_aunt  \
1160              0             0               0             0           0   
1165              0             0               0             0           0   
1167              0             0               0             0           0   
1168              0             0               0             0           0   
1169              0             0               0             0           0   
...             ...           ...             ...           ...         ...   
1687              0             0               0             0           0   
1689              0             0               0             0           0   
1690              0             0               0             0           0   
1691              0             0               0             0           0   
1693              0             0               0             0           0   

     nrelbc_grandma  nrelbc_absent  
1160              0              1  
1165              0              1  
1167              0              1  
1168              0              1  
1169              0              1  
...             ...            ...  
1687              0              1  
1689              0              1  
1690              0              1  
1691              0              1  
1693              0              1  

[276 rows x 29 columns]

In [192]:
# Handling missing values in the allergies data
# Replacing missing values with the "No" value
df.fillna({"allergies" : "No"}, inplace = True)

# Viewing the amount of missing values in the allergies data
df["allergies"].isnull().sum()

0

In [193]:
# Viewing the unique values of the allergies column
df["allergies"].unique()

array(['Rhinitis', 'Medicines', 'Laryngitis', 'No', 'Dermatitis', 'Other',
       'Medicines/Other', 'Dermatitis/Rhinitis', 'Medicines/Rhinitis',
       'Medicines/Rhinitis/Laryngitis', 'Medicines/Rhinitis/Other',
       'Rhinitis/Laryngitis', 'Dermatitis/Rhinitis/Laryngitis',
       'Rhinitis/Other', 'Dermatitis/Rhinitis/Other',
       'Rhinitis/Laryngitis/Medicines', 'Laryngitis/Other',
       'Dermatitis/Rhinitis/Medicines', 'Rhinitis/Medicines',
       'Dermatitis/Medicines/Other', 'Laryngitis/Medicines',
       'Rhinitis/Laryngitis/Other', 'Dermatitis/Laryngitis',
       'Dermatitis/Rhinitis/Laryngitis/Medicines/Other'], dtype=object)

In [194]:
# Creating new columns to identify which allergies exist in patients
# Identifying available values
allergies = ["Rhinitis", "Medicines", "Laryngitis", "Dermatitis", "Other", "No"]

# Creating the new columns
for allergy in allergies:
    df[allergy] = df["allergies"].str.contains(allergy).astype(int)

# Dropping the original column
df.drop(columns = ["allergies"], inplace = True)

In [195]:
# Renaming the result columns
df = df.rename(columns = {
    "Rhinitis" : "rhinitis_allergy",
    "Medicines" : "medicines_allergy",
    "Laryngitis" : "laryngitis_allergy",
    "Dermatitis" : "dermatitis_allergy",
    "Other" : "other_allergy",
    "No" : "no_allergy"
})

In [196]:
# Viewing the amount of unique values in each column
df.nunique()

id                    1697
age                     61
menarche                10
menopause               28
agefirst                32
children                 7
breastfeeding           28
biopsies                 6
hyperplasia              2
race                     3
year                    18
imc                    188
weight                 292
exercise                 9
alcohol                  2
tobacco                  2
emotional                2
depressive               2
histologicalclass       11
birads                   7
cancer                   2
nrelbc_mother            2
nrelbc_sister            2
nrelbc_daughter          2
nrelbc_cousin            2
nrelbc_aunt              2
nrelbc_grandma           2
nrelbc_absent            2
rhinitis_allergy         2
medicines_allergy        2
laryngitis_allergy       2
dermatitis_allergy       2
other_allergy            2
no_allergy               2
dtype: int64

## Handling missing values for data with low significance
Columns processed: "year", "biopsies", "imc", "weight"

In [197]:
# Handling missing values in the year data
yearMedian = df["year"].median()
df.fillna({"year" : yearMedian}, inplace = True)

# Viewing the amount of null values in the year data
df["year"].isnull().sum()

0

In [198]:
# Removing rows with missing values in all columns except for the histologicalclass and birads columns
df = df.drop(columns = ["histologicalclass", "birads"]).dropna().join(df["histologicalclass"]).join(df["birads"])
# Columns affected: "biopsies", "imc", "weight"

In [199]:
# Viewing the amount of null values in each column
df.isnull().sum()

id                      0
age                     0
menarche                0
menopause               0
agefirst                0
children                0
breastfeeding           0
biopsies                0
hyperplasia             0
race                    0
year                    0
imc                     0
weight                  0
exercise                0
alcohol                 0
tobacco                 0
emotional               0
depressive              0
cancer                  0
nrelbc_mother           0
nrelbc_sister           0
nrelbc_daughter         0
nrelbc_cousin           0
nrelbc_aunt             0
nrelbc_grandma          0
nrelbc_absent           0
rhinitis_allergy        0
medicines_allergy       0
laryngitis_allergy      0
dermatitis_allergy      0
other_allergy           0
no_allergy              0
histologicalclass     526
birads                526
dtype: int64

## Preparing data needed for imputation

In [200]:
# Viewing which columns are categorical
df.select_dtypes(include = "object").apply(pd.unique)

children                 [0, 1, 2, 3, 4, 5, 5+]
hyperplasia                           [Yes, No]
race                      [White, Mixed, Black]
alcohol                               [Yes, No]
tobacco                               [Yes, No]
emotional                            [Sad, Joy]
depressive                            [Yes, No]
cancer                                [Yes, No]
birads         [3A, 3B, 4B, 3C, 5C, 5B, 6, nan]
dtype: object

In [201]:
# Encoding categorical data using one hot encoding
oneHotChildren = pd.get_dummies(df["children"], drop_first = True)
oneHotHyperplasia = pd.get_dummies(df["hyperplasia"], drop_first = True)
oneHotRace = pd.get_dummies(df["race"], drop_first = True)
oneHotAlcohol = pd.get_dummies(df["alcohol"], drop_first = True)
oneHotTobacco = pd.get_dummies(df["tobacco"], drop_first = True)
oneHotEmotional = pd.get_dummies(df["emotional"], drop_first = True)
oneHotDepressive = pd.get_dummies(df["depressive"], drop_first = True)
oneHotCancer = pd.get_dummies(df["cancer"], drop_first = True)

In [202]:
# Renaming the columns
oneHotChildren = oneHotChildren.rename(columns = {
    "1" : "1_children",
    "2" : "2_children",
    "3" : "3_children",
    "4" : "4_children",
    "5" : "5_children",
    "5+" : "more_than_5_children"
})

oneHotHyperplasia = oneHotHyperplasia.rename(columns = {
    "Yes" : "hyperplasia"
})

oneHotRace = oneHotRace.rename(columns = {
    "Mixed" : "is_mixed_race",
    "White" : "is_white_race"
})

oneHotAlcohol = oneHotAlcohol.rename(columns = {
    "Yes" : "consumed_alcohol"
})

oneHotTobacco = oneHotTobacco.rename(columns = {
    "Yes" : "consumed_tobacco"
})

oneHotEmotional = oneHotEmotional.rename(columns = {
    "Sad" : "is_sad"
})

oneHotDepressive = oneHotDepressive.rename(columns = {
    "Yes" : "is_depressive"
})

oneHotCancer = oneHotCancer.rename(columns = {
    "Yes" : "cancer"
})

In [203]:
# Selecting relevant non categorical features for imputation
relevantDf = df.select_dtypes(exclude = "object")
relevantDf["birads"] = df["birads"]

# Combining all relevant features and newly encoded data into one dataframe
preppedDf = pd.concat([relevantDf, oneHotChildren, oneHotHyperplasia, oneHotRace, oneHotAlcohol,
                       oneHotTobacco, oneHotEmotional, oneHotDepressive, oneHotCancer], axis = 1)
preppedDf.nunique()

id                      1686
age                       61
menarche                  10
menopause                 28
agefirst                  32
breastfeeding             28
biopsies                   6
year                      18
imc                      188
weight                   292
exercise                   9
nrelbc_mother              2
nrelbc_sister              2
nrelbc_daughter            2
nrelbc_cousin              2
nrelbc_aunt                2
nrelbc_grandma             2
nrelbc_absent              2
rhinitis_allergy           2
medicines_allergy          2
laryngitis_allergy         2
dermatitis_allergy         2
other_allergy              2
no_allergy                 2
histologicalclass         11
birads                     7
1_children                 2
2_children                 2
3_children                 2
4_children                 2
5_children                 2
more_than_5_children       2
hyperplasia                2
is_mixed_race              2
is_white_race 

## Handling histologicalclass missing values using random forest imputation

In [204]:
# Selecting required columns for imputation
histImputeDf = preppedDf.drop(["birads"], axis = 1)
histImputeDf

id  age  menarche  menopause  agefirst  breastfeeding  biopsies  \
0        1   50        11         -1        -1             -1       1.0   
1        2   46        12         -1        36              3       2.0   
2        3   47        13         -1        26              3       1.0   
3        4   49        11         47        21             -1       1.0   
4        5   54        14         42        16              1       2.0   
...    ...  ...       ...        ...       ...            ...       ...   
1692  1693   42        12         32        20              3       0.0   
1693  1694   21        12         -1        -1             -1       0.0   
1694  1695   21         9         -1        -1             -1       0.0   
1695  1696   25        12         -1        -1             -1       0.0   
1696  1697   20        11         -1        -1             -1       0.0   

        year   imc  weight  ...  5_children  more_than_5_children  \
0     2011.0  27.6    83.4  ...       False                 False   
1     2013.0  27.3    78.2  ...       False                 False   
2     2011.0  24.6    82.6  ...       False                 False   
3     2011.0  28.6    79.4  ...       False                 False   
4     2007.0  28.4    81.5  ...       False                 False   
...      ...   ...     ...  ...         ...                   ...   
1692  2011.0  22.0    60.0  ...       False                 False   
1693  2011.0  22.9    70.0  ...       False                 False   
1694  2011.0  20.7    55.0  ...       False                 False   
1695  2011.0  23.9    69.0  ...       False                 False   
1696  2011.0  23.4    67.7  ...       False                 False   

      hyperplasia  is_mixed_race  is_white_race  consumed_alcohol  \
0            True          False           True              True   
1            True           True          False              True   
2            True          False          False             False   
3           False          False          False              True   
4            True          False           True              True   
...           ...            ...            ...               ...   
1692        False          False           True              True   
1693        False          False           True             False   
1694        False          False           True              True   
1695        False           True          False              True   
1696        False          False           True             False   

      consumed_tobacco  is_sad  is_depressive  cancer  
0                 True    True           True    True  
1                False   False          False    True  
2                 True    True          False    True  
3                 True   False          False    True  
4                False    True           True    True  
...                ...     ...            ...     ...  
1692             False   False          False   False  
1693             False   False          False   False  
1694              True   False          False   False  
1695              True   False          False   False  
1696             False   False          False   False  

[1686 rows x 39 columns]

In [205]:
# Splitting data into complete data and data with missing histologicalclass values
histTrainDf = histImputeDf.loc[~df.isnull().any(axis = 1)]
histTestDf = histImputeDf.loc[df.isnull().any(axis = 1)]

In [206]:
# Initializing the model
rf_hist = RandomForestRegressor()

# Selecting relevant features
features = histImputeDf.drop(columns = ["histologicalclass", "id"]).columns.tolist()

# Training the model
rf_hist.fit(histTrainDf[features], histTrainDf["histologicalclass"])

RandomForestRegressor()

In [207]:
# Prediciting the missing histologicalclass values
pred_hist = rf_hist.predict(histTestDf[features])
pred_hist

array([4.56, 3.77, 4.29, 4.37, 3.52, 4.47, 5.8 , 5.1 , 5.36, 4.58, 5.18,
       4.88, 4.56, 3.82, 4.83, 5.37, 5.07, 4.91, 4.3 , 4.13, 4.25, 4.17,
       3.73, 6.02, 3.99, 4.43, 5.85, 5.46, 4.63, 4.7 , 4.27, 3.9 , 3.58,
       4.66, 4.89, 4.34, 4.8 , 4.44, 4.79, 5.52, 5.45, 4.01, 4.35, 5.01,
       5.45, 4.96, 5.45, 4.74, 3.9 , 5.  , 5.58, 4.26, 5.25, 5.66, 4.45,
       3.6 , 4.25, 4.03, 5.09, 5.2 , 3.52, 5.22, 4.56, 5.57, 4.58, 4.49,
       4.06, 4.44, 3.72, 3.82, 3.89, 4.33, 4.87, 3.91, 4.14, 3.66, 3.86,
       4.54, 5.42, 4.47, 3.7 , 5.38, 4.08, 4.6 , 3.7 , 5.13, 4.81, 5.13,
       5.07, 4.01, 4.64, 4.97, 4.35, 4.33, 3.99, 3.63, 5.6 , 4.81, 4.26,
       3.78, 4.35, 4.35, 4.1 , 4.08, 5.53, 4.75, 5.04, 5.46, 4.25, 4.99,
       3.98, 3.79, 4.96, 4.65, 3.57, 4.34, 5.24, 3.87, 4.77, 4.37, 3.97,
       3.65, 4.44, 4.02, 5.63, 5.01, 3.64, 4.71, 3.76, 3.91, 4.4 , 4.53,
       3.89, 4.08, 3.74, 5.  , 5.25, 3.92, 4.32, 4.69, 5.89, 4.45, 5.28,
       4.56, 5.33, 4.47, 5.49, 4.37, 3.83, 4.7 , 4.

In [208]:
# Rounding float values from prediction and changing the values to integer
pred_hist = pred_hist.round(0)
pred_hist

array([5., 4., 4., 4., 4., 4., 6., 5., 5., 5., 5., 5., 5., 4., 5., 5., 5.,
       5., 4., 4., 4., 4., 4., 6., 4., 4., 6., 5., 5., 5., 4., 4., 4., 5.,
       5., 4., 5., 4., 5., 6., 5., 4., 4., 5., 5., 5., 5., 5., 4., 5., 6.,
       4., 5., 6., 4., 4., 4., 4., 5., 5., 4., 5., 5., 6., 5., 4., 4., 4.,
       4., 4., 4., 4., 5., 4., 4., 4., 4., 5., 5., 4., 4., 5., 4., 5., 4.,
       5., 5., 5., 5., 4., 5., 5., 4., 4., 4., 4., 6., 5., 4., 4., 4., 4.,
       4., 4., 6., 5., 5., 5., 4., 5., 4., 4., 5., 5., 4., 4., 5., 4., 5.,
       4., 4., 4., 4., 4., 6., 5., 4., 5., 4., 4., 4., 5., 4., 4., 4., 5.,
       5., 4., 4., 5., 6., 4., 5., 5., 5., 4., 5., 4., 4., 5., 4., 3., 3.,
       5., 3., 3., 5., 4., 6., 6., 4., 3., 4., 3., 4., 4., 5., 4., 5., 4.,
       4., 5., 4., 4., 4., 4., 4., 4., 4., 5., 4., 5., 5., 4., 4., 5., 5.,
       3., 5., 5., 5., 4., 4., 4., 4., 4., 4., 3., 4., 4., 5., 5., 6., 4.,
       4., 5., 4., 4., 4., 5., 5., 5., 4., 4., 5., 4., 4., 4., 4., 4., 5.,
       5., 5., 4., 4., 4.

In [209]:
# Joining the results with the test dataframe
histTestDf.loc[:, "histologicalclass"] = pred_hist
histTestDf["histologicalclass"].value_counts()

histologicalclass
4.0    270
5.0    192
6.0     47
3.0     15
7.0      2
Name: count, dtype: int64

In [210]:
# Joining the test dataframe with the training dataframe
newImputedDf = pd.concat([histTrainDf, histTestDf], ignore_index = True)
newImputedDf = newImputedDf.sort_values(by = "id", ascending = True)

# Rejoining the birads column that got dropped
newImputedDf["birads"] = preppedDf["birads"]

## Handling birads missing values using random forest imputation

In [211]:
# Viewing the unique values of birads
newImputedDf["birads"].unique()

array(['3A', '3B', '4B', '3C', '5C', '5B', '6', nan], dtype=object)

In [212]:
# Encoding birads' categorical data
biradsMap = {
    "3A" : 1,
    "3B" : 2,
    "3C" : 3,
    "4B" : 4,
    "5B" : 5,
    "5C" : 6,
    "6" : 7
}
newImputedDf.loc[:, "birads"] = newImputedDf["birads"].map(biradsMap).fillna(0).astype(int)
newImputedDf["birads"].value_counts()

birads
0    526
5    315
6    239
2    232
4    194
3     97
7     57
1     26
Name: count, dtype: int64

In [213]:
# Converting the birads column into float
newImputedDf["birads"] = newImputedDf["birads"].astype(float)
newImputedDf["birads"].value_counts()

birads
0.0    526
5.0    315
6.0    239
2.0    232
4.0    194
3.0     97
7.0     57
1.0     26
Name: count, dtype: int64

In [214]:
# Splitting data into complete data and data with missing birads values
birTrainDf = newImputedDf.loc[newImputedDf["birads"] != 0.0]
birTestDf = newImputedDf.loc[newImputedDf["birads"] == 0.0]

In [215]:
# Initializing the model
rf_bir = RandomForestRegressor()

# Selecting relevant features
features = newImputedDf.drop(columns = ["birads", "id"]).columns.tolist()

# Training the model
rf_bir.fit(birTrainDf[features], birTrainDf["birads"])

RandomForestRegressor()

In [216]:
# Prediciting the missing histologicalclass values
pred_bir = rf_bir.predict(birTestDf[features])
pred_bir

array([3.33, 2.91, 2.96, 2.9 , 3.63, 3.24, 4.22, 4.44, 4.46, 3.78, 3.1 ,
       3.21, 2.92, 3.46, 3.6 , 3.58, 3.57, 3.16, 4.06, 3.84, 3.08, 3.94,
       4.57, 3.29, 3.65, 4.17, 4.02, 3.99, 3.93, 3.15, 3.18, 3.57, 4.14,
       3.42, 3.  , 4.03, 2.96, 3.28, 3.15, 3.62, 3.62, 3.56, 2.88, 3.26,
       4.22, 3.8 , 3.24, 4.94, 4.12, 3.59, 3.59, 4.09, 4.65, 3.3 , 2.88,
       3.05, 4.44, 3.54, 3.18, 3.4 , 3.3 , 3.3 , 3.54, 3.71, 3.85, 3.83,
       3.1 , 4.09, 4.36, 4.2 , 2.69, 4.44, 3.41, 3.64, 3.55, 4.13, 3.72,
       2.84, 3.45, 3.32, 3.16, 3.51, 3.27, 4.14, 4.1 , 3.44, 4.06, 3.34,
       4.05, 4.37, 4.08, 3.87, 3.7 , 3.72, 3.15, 3.88, 3.08, 3.05, 3.63,
       3.51, 4.06, 3.88, 4.22, 3.01, 4.26, 3.25, 3.6 , 3.1 , 4.12, 3.73,
       4.01, 2.84, 3.55, 3.56, 3.34, 3.62, 3.59, 3.92, 3.82, 3.23, 3.66,
       3.29, 4.04, 4.23, 3.64, 3.11, 3.88, 3.19, 3.7 , 4.19, 3.78, 4.01,
       3.41, 5.19, 2.9 , 4.5 , 3.35, 4.09, 3.56, 3.72, 4.03, 4.04, 3.89,
       3.04, 3.85, 3.16, 3.68, 4.07, 2.98, 4.36, 3.

In [217]:
# Rounding float values from prediction and changing the values to integer
pred_bir = pred_bir.round(0)
pred_bir

array([3., 3., 3., 3., 4., 3., 4., 4., 4., 4., 3., 3., 3., 3., 4., 4., 4.,
       3., 4., 4., 3., 4., 5., 3., 4., 4., 4., 4., 4., 3., 3., 4., 4., 3.,
       3., 4., 3., 3., 3., 4., 4., 4., 3., 3., 4., 4., 3., 5., 4., 4., 4.,
       4., 5., 3., 3., 3., 4., 4., 3., 3., 3., 3., 4., 4., 4., 4., 3., 4.,
       4., 4., 3., 4., 3., 4., 4., 4., 4., 3., 3., 3., 3., 4., 3., 4., 4.,
       3., 4., 3., 4., 4., 4., 4., 4., 4., 3., 4., 3., 3., 4., 4., 4., 4.,
       4., 3., 4., 3., 4., 3., 4., 4., 4., 3., 4., 4., 3., 4., 4., 4., 4.,
       3., 4., 3., 4., 4., 4., 3., 4., 3., 4., 4., 4., 4., 3., 5., 3., 4.,
       3., 4., 4., 4., 4., 4., 4., 3., 4., 3., 4., 4., 3., 4., 4., 4., 5.,
       4., 4., 4., 4., 5., 4., 4., 3., 4., 4., 5., 4., 4., 3., 4., 4., 5.,
       4., 3., 3., 3., 4., 3., 4., 3., 4., 4., 3., 4., 3., 3., 4., 3., 4.,
       4., 3., 4., 4., 3., 4., 4., 4., 3., 3., 4., 3., 4., 4., 4., 3., 5.,
       4., 4., 4., 3., 4., 4., 3., 4., 4., 4., 4., 5., 4., 4., 3., 4., 4.,
       4., 4., 3., 4., 4.

In [218]:
# Joining the results with the test dataframe
birTestDf.loc[:, "birads"] = pred_bir
birTestDf.loc[:, "birads"] = birTestDf["birads"].astype(int)
birTestDf["birads"].value_counts()

birads
4.0    296
3.0    203
5.0     27
Name: count, dtype: int64

In [219]:
# Joining the test dataframe with the training dataframe
FINAL_DF = pd.concat([birTrainDf, birTestDf], ignore_index = True)
FINAL_DF = FINAL_DF.sort_values(by = "id", ascending = True)

In [220]:
# Last check for null values
FINAL_DF.isnull().sum()

id                      0
age                     0
menarche                0
menopause               0
agefirst                0
breastfeeding           0
biopsies                0
year                    0
imc                     0
weight                  0
exercise                0
nrelbc_mother           0
nrelbc_sister           0
nrelbc_daughter         0
nrelbc_cousin           0
nrelbc_aunt             0
nrelbc_grandma          0
nrelbc_absent           0
rhinitis_allergy        0
medicines_allergy       0
laryngitis_allergy      0
dermatitis_allergy      0
other_allergy           0
no_allergy              0
histologicalclass       0
1_children              0
2_children              0
3_children              0
4_children              0
5_children              0
more_than_5_children    0
hyperplasia             0
is_mixed_race           0
is_white_race           0
consumed_alcohol        0
consumed_tobacco        0
is_sad                  0
is_depressive           0
cancer      

# Saving the preprocessed dataset

In [221]:
FINAL_DF.to_csv("dataset/PreprocessedDataset.csv", index = False)

In [222]:
FINAL_DF.dtypes

id                        int64
age                       int64
menarche                  int64
menopause                 int32
agefirst                  int32
breastfeeding             int32
biopsies                float64
year                    float64
imc                     float64
weight                  float64
exercise                  int32
nrelbc_mother             int32
nrelbc_sister             int32
nrelbc_daughter           int32
nrelbc_cousin             int32
nrelbc_aunt               int32
nrelbc_grandma            int32
nrelbc_absent             int32
rhinitis_allergy          int32
medicines_allergy         int32
laryngitis_allergy        int32
dermatitis_allergy        int32
other_allergy             int32
no_allergy                int32
histologicalclass       float64
1_children                 bool
2_children                 bool
3_children                 bool
4_children                 bool
5_children                 bool
more_than_5_children       bool
hyperpla